# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           date

# Setup
title:               Mike Lo
tagline:             Design and Data Science
description:         Personal Blog
# url:                 http://lanyon.getpoole.com
# url:                 http://yuanhunglo.com
# url:                 http://www.yuanhunglo.com/blog
baseurl:             http://yuanhunglo.github.io/blog
# baseurl:             ''
paginate:            5
port:                4444

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# gems: [jekyll-paginate]
#  paginate_path: "page:num" 

# theme: jekyll-theme-cayman
