# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hellomikelo
description: Mike Lo's Blog on Data Science and Design

url: "www.hellomikelo.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
# site_url: 

# twitter_username: hellomikelo
github_username:  yuanhunglo
linkedin_username: mike-yhl 
email: hellomikelo@gmail.com

# Build settings
# markdown: kramdown
# highlighter: rouge

# plugins: [jekyll-paginate, jekyll-seo-tag]
#gems:
#  - jekyll-assets


port: 4444
# collections:
#   projects:
#     output: true
#     permalink: /:collection/:name