# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yuanhung Lo
email: lo.yuanhung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal journey 

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# twitter_username: briancaffey
github_username:  yuanhunglo
linkedin_username: yuan-hung-lo-a8915551
linkedin_name: Yuanhung Lo

# Build settings
markdown: kramdown
highlighter: rouge

#gems:
#  - jekyll-assets

port: 4444
# collections:
#   projects:
#     output: true
#     permalink: /:collection/:name