permalink: pretty

# Setup
title:               Mike Lo
tagline:             "Data + Urbanism"
description:         "Mike's Blog"
# url:                 http://yuanhunglo.github.io
#baseurl:             http://yuanhunglo.github.io/blog/
url: "http://yuanhunglo.github.io/blog"
# baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mike Lo
  url:               https://yuanhunglo.com
  email:             lo.yuanhung@gmail.com

# Custom vars
version:             1.0.0


