# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# url:                 http://yuanhunglo.github.io
baseurl:             http://yuanhunglo.github.io/blog
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0



# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           date
#permalink:           pretty
#relative_permalinks: true

# Setup
#title:               Mike Lo
#tagline:             Design and Data Science
#description:         ''
# url:                 http://yuanhunglo.github.io 
# url:                 http://127.0.0.1:4444
# baseurl:             '/blog/'
#baseurl:             http://yuanhunglo.github.io/blog

#paginate:            5
#port:                4444

# About/contact
# author:
#  name:              Mark Otto
#  url:               https://twitter.com/mdo
#  email:             markdotto@gmail.com

# Custom vars
#version:             1.0.0

#gems: [jekyll-paginate]
#  paginate_path: "/blog/page:num" 

# theme: jekyll-theme-cayman
