permalink:           /:categories/:year/:month/:day/:title:output_ext

# Setup
title:               Yuanhung (Mike) Lo
tagline:             "Data + Urbanism"
description:         "Mike's Blog" 
url:                 "http://yuanhunglo.github.io/blog/"  # main URL to the blog
# baseurl:             ''
paginate:            5  # how many posts to show on the page

# About/contact
author:
  name:              Mike Lo
  url:               https://www.yuanhunglo.com
  email:             lo.yuanhung@gmail.com

# Custom vars
version:             1.0.0


