permalink: pretty

# Setup
title:               Mike Lo
tagline:             "Design and Data Science"
description:         "Mike's Blog"
# url:                 http://yuanhunglo.github.io
#baseurl:             http://yuanhunglo.github.io/blog/
url: "http://yuanhunglo.github.io/blog"
# baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0


