# The ":" in front means the word is a variable. The order can be changed to have a different format
permalink:           /:categories/:year/:month/:day/:title:output_ext

# Setup
title:               "Data + Sustainable Urbanism"
tagline:             "A blog by Mike Lo"
description:         "Data science and the development of sustainable smart cities" 
url:                 "http://yuanhunglo.github.io/blog/"  # main URL to the blog
paginate:            5  # how many posts to show on the page

theme: simple

# About/contact
author:
  name:              Mike Lo
  url:               https://www.yuanhunglo.com
  email:             lo.yuanhung@gmail.com

# Custom vars
version:             1.0.0

# For local Jekyll serving
port:                4444
plugins: [jekyll-paginate]
paginate_path: "/blog/page:num" 
